### ISSUE TITLE
Add instances of the trajectories

### ISSUE THREAD

**Issue by baptistemc** [baptistemc/OptimalPrecision#9]
Add instances as in ANR-REM_data/AnticipationPursuit/Data_analysis/Oldies/2016-09-08%20Harris%20%26%20Wolpert_Testing%20the%20linear%20model.ipynb

Starting from an optimal trajectory obtained by Harris and Wolpert's method, the signal is disturbed with a multiplicative noise k|Ut|².

**Comment by laurentperrinet** [comment]
just did it by anticipation! :-)
